<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\App\PayFlow.Application\PayFlow.Application.csproj" />
    <ProjectReference Include="..\..\Domain\PayFlow.Domain.Interface\PayFlow.Domain.Interface.csproj" />
    <ProjectReference Include="..\..\Domain\PayFlow.Domain\PayFlow.Domain.csproj" />
  </ItemGroup>

</Project>
